services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NUXT_PORT:-3000}:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    container_name: ${TRIGRAM:-DCK}_nuxt-app

  cypress:
    image: cypress/included:latest
    container_name: ${TRIGRAM:-DCK}_cypress
    volumes:
      - .:/e2e
    working_dir: /e2e
