name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 80:80

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install
          npm install ts-node typescript --save-dev  # Installe ts-node et typescript

      - name: Build and start services with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Run Cypress tests
        run: |
          docker-compose run --rm --remove-orphans cypress -b chrome --headless

      - name: Stop Docker Compose services
        run: |
          docker-compose down
